load_module modules/ngx_http_lua_module.so;

env LUA_DIR;

http{

    lua_package_path "$LUA_DIR/?.lua;;";

    server{
        listen 80;

        location /lua_test {
            default_type text/plain;
            content_by_lua_file $LUA_DIR/test.lua;
        }
    }
}