events{
}

http{

    lua_package_path "/etc/nginx/lua/?.lua;;";

    server{
        listen 80;

        location /lua_test {
            default_type text/plain;
            content_by_lua_file /etc/nginx/lua/test.lua;
        }
    }
}