env LUA_DIR=/usr/local/openresty/nginx/conf/lua;

events{}

http{

    server{
        listen 80;

        location /lua_test {
            default_type text/plain;
            content_by_lua_block {
              local dir = os.getenv("LUA_DIR")
              local f = dofile(dir .. "/test.lua")
              f()
            }
        }
    }
}