env LUA_DIR=/usr/local/openresty/nginx/conf/lua;
events{}

http{

    server{
        listen 80;

        set $access_token "";

        location /lua_test {

            default_type text/plain;
            content_by_lua_block {
              local dir = os.getenv("LUA_DIR")
              local f = dofile(dir .. "/test.lua")
              f()
            }
        }

        location /.well-known/acme-challenge {
            root /usr/local/openresty/nginx/conf/lua;
        }

         location = / {

            access_by_lua_block {
              local dir = os.getenv("LUA_DIR")
              local f = dofile(dir .. "/token.lua")
              local token = f()
              ngx.var.access_token = token
            }

            proxy_pass https://robotshopdevweb.blob.core.windows.net/static/index.html;
            proxy_set_header Authorization "Bearer $access_token";
            proxy_set_header x-ms-version 2020-08-04;
        }

        location / {

            access_by_lua_block {
              local dir = os.getenv("LUA_DIR")
              local f = dofile(dir .. "/token.lua")
              local token = f()
              ngx.var.access_token = token
            }

            proxy_pass https://robotshopdevweb.blob.core.windows.net/static/;
            proxy_set_header Authorization "Bearer $access_token";
            proxy_set_header x-ms-version 2020-08-04;
        }

        location /api/ {

            proxy_pass http://10.0.4.12:30688/;
        }

        location /prometheus/ {

            proxy_pass http://10.0.4.12:30688/prometheus/;
        }
    }

    server{
        listen 443 ssl;

        ssl_certificate /usr/local/openresty/nginx/conf/certs/robotshopappinfullchain.pem
        ssl_certificate_key /usr/local/openresty/nginx/conf/certs/robotshopappinkey.pem

        location /lua_test {

            default_type text/plain;
            content_by_lua_block {
              local dir = os.getenv("LUA_DIR")
              local f = dofile(dir .. "/test.lua")
              f()
            }
        }
    }
}