name: Validate and Push Openresty configuration to Development

on:
  push:
    branches-ignore:
      - main  

  pull_request:
    branches:
      - develop

  workflow_dispatch:

jobs:
  deploy:
    uses: robot-shop-DevOps/robot-shop-github-actions/.github/workflows/openresty.yaml@main
    with:
      LUA_DIR: ./httplua
      OPENRESTY_DIR: ./openresty
    secrets: inherit